name: Tests

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "docs/**"
      - ".gitignore"
      - ".gitmodules"
    branches: [ "master" ]
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "docs/**"
      - ".gitignore"
      - ".gitmodules"
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.2.4
      with:
        # Space delimited list of packages to install.
        packages: libsfml-dev libbox2d-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=Debug
    
#    - name: Cache
#      uses: actions/cache@v3.0.11
#      with:
#        # A list of files, directories, and wildcard patterns to cache and restore
#        path: ${{github.workspace}}/build
#        # An explicit key for restoring and saving the cache
#        key: ${{ runner.os }}-build

    - name: Build
      working-directory: ${{github.workspace}}
      # Build your program with the given configuration
      run: cmake --build ./build --config Debug --target CementEngineTests

    - name: Test
      working-directory: ${{github.workspace}}
      run: ./build/CementEngineTests
